
export const LOGIN_DATA = 'LOGIN_DATA'

// category types
export const CATEGORY_DATA = 'CATEGORY_DATA'
export const CATEGORY_LIST_DATA = 'CATEGORY_LIST_DATA'
export const CATEGORY_DELETE_DATA = 'CATEGORY_DELETE_DATA'
export const CATEGORY_UPDATE_DATA = 'CATEGORY_UPDATE_DATA'

// sub-category types
export const SUB_CATEGORY_DATA = 'SUB_CATEGORY_DATA' 
export const SUB_CATEGORY_LIST_DATA = 'SUB_CATEGORY_LIST_DATA' 
export const SUB_CATEGORY_DELETE_DATA = 'SUB_CATEGORY_DELETE_DATA'
export const SUB_CATEGORY_UPDATE_DATA = 'SUB_CATEGORY_UPDATE_DATA'
export const SUB_CATEGORY_DETAILED_LIST_DATA = 'SUB_CATEGORY_DETAILED_LIST_DATA'

// service types
export const SERVICE_DATA = 'SERVICE_DATA'
export const SERVICE_LIST_DATA = 'SERVICE_LIST_DATA'
export const SERVICE_DELETE_DATA = 'SERVICE_DELETE_DATA'
export const SERVICE_UPDATE_DATA = 'SERVICE_UPDATE_DATA'

// image types
export const IMAGE_DATA = 'IMAGE_DATA'
export const IMAGE_LIST_DATA = 'IMAGE_LIST_DATA'
export const IMAGE_DELETE_DATA = 'IMAGE_DELETE_DATA'
export const IMAGE_UPDATE_DATA = 'IMAGE_UPDATE_DATA'

// vendor signup
export const VENDOR_DATA = 'VENDOR_DATA'
